### ISSUE TITLE
Hotbat shit

### ISSUE THREAD

**Issue by kubikwtf** [MinemenFree/Practice#32]
[19:15:51 ERROR]: Error occurred while enabling cPractice v1.1.5 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "rip.crystal.practice.player.profile.hotbar.entry.HotbarEntry.getItemStack()" because the return value of "java.util.Map.get(Object)" is null
        at rip.crystal.practice.player.profile.hotbar.Hotbar.init(Hotbar.java:57) ~[?:?]
        at rip.crystal.practice.cPractice.initManagers(cPractice.java:199) ~[?:?]
        at rip.crystal.practice.cPractice.onEnable(cPractice.java:153) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[server.jar:git-Spigot-8055d5e-unknown]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [server.jar:git-Spigot-8055d5e-unknown]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [server.jar:git-Spigot-8055d5e-unknown]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:358) [server.jar:git-Spigot-8055d5e-unknown]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [server.jar:git-Spigot-8055d5e-unknown]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [server.jar:git-Spigot-8055d5e-unknown]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [server.jar:git-Spigot-8055d5e-unknown]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [server.jar:git-Spigot-8055d5e-unknown]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [server.jar:git-Spigot-8055d5e-unknown]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [server.jar:git-Spigot-8055d5e-unknown]
        at java.lang.Thread.run(Thread.java:833) [?:?]
        
        
        
        
    - >     My java skills didnt that good to fix this.

**Comment by gabrielvicenteYT** [comment]
I don't exactly know the issue, but I know that it's urgent

**Comment by RainFallDev** [comment]
Use supported spigot or use eden batter

**Comment by gabrielvicenteYT** [comment]
Eden is better as of now
